application: warcards-1331
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: api.app

- url: /crons/send_reminder
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest
